name: CI (Data Analysis)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Jupyter + dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/data-exploration-and-visualization.ipynb --output run.ipynb
          jupyter nbconvert --to html run.ipynb --output report.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis-outputs
          path: |
            run.ipynb
            report.html
