name: CI (Data Analysis)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # يجلب كود الريبو
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # يثبّت بايثون ويضيفه للـ PATH
      - name: Debug: where am I & what files?
        run: |
          pwd
          ls -R
      - name: Install Jupyter + deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert ipykernel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute notebook
        run: |
          jupyter nbconvert \
            --to notebook --execute path/to/your-notebook.ipynb \
            --output run.ipynb \
            --ExecutePreprocessor.timeout=1800 \
            --log-level=INFO
      - name: Export HTML report
        run: jupyter nbconvert --to html run.ipynb --output report.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis-outputs
          path: |
            run.ipynb
            report.html
          if-no-files-found: warn
