name: CI (Data Analysis)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout
      uses: actions/checkout@v4

      
name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

      
name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('*/requirements.txt') }}
        restore-keys: |${{ runner.os }}-pip-

      
name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # شغّلي نوتبوك أو سكربت التحليل
      # مثال للنوتبوك (اختياري إذا عندك notebooks):
      # - name: Execute notebook
      #   run: |
      #     pip install jupyter nbconvert
      #     jupyter nbconvert --to notebook --execute notebooks/analysis.ipynb --output run.ipynb
      #     jupyter nbconvert --to html run.ipynb --output report.html

      
name: Run analysis script (optional)
      run: |
        if [ -f scripts/run_analysis.py ]; then python scripts/run_analysis.py; fi

      
name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analysis-outputs
        path: |
          reports/
          outputs/
        if-no-files-found: ignore


